Feature/crud cost center
tx-services-Internship/travel-java-backend-monolith-spyro pull request #5
Opened 2022-11-25 09:27 UTC by markolu

2022-11-25 13:54 UTC, megicivovic requested changes
Couple of cosmetic changes only 🧹  God work on exception handling and mapping!

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/controller/CostCenterController.java
> +@RequestMapping("/api/cost-centers")
have a look at this [comment](https://github.com/tx-services-Internship/travel-java-backend-monolith-spyro/pull/4#discussion_r1031729324)

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/controller/CostCenterController.java
> +      final CostCenterServiceImplementation costCenterService,
here should be interface `CostCenterService`

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/controller/CostCenterController.java
> +  public ResponseEntity<?> deleteCostCenterById(@PathVariable("id") Long id) {
maybe you can remove the wildcard since you no it will be with no content

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/service/exception/CostCenterCodeAlreadyExists.java
> +  public CostCenterCodeAlreadyExists(final String code) {
```suggestion
  public CostCenterCodeAlreadyExistsException(final String code) {
```

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/service/exception/CostCenterNotPresent.java
> +public class CostCenterNotPresent extends RuntimeException {
```suggestion
public class CostCenterNotPresentException extends RuntimeException {
```

2022-11-25 13:54 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/mapper/CostCenterMapperImplementation.java
> +public class CostCenterMapperImplementation {
```suggestion
public class CostCenterMapper {
```
since there is no interface, it doen't need to have "implementation" in the name

2022-11-28 15:48 UTC, megicivovic reviewed
Amazing work! 🚀  Just add that test please!

2022-11-28 15:48 UTC, megicivovic commented on travel/src/main/java/com/tx/travel/controller/CostCenterController.java
> +  public ResponseEntity<CostCenterResponse> saveCostCenter(
maybe name it createCostCenter

2022-11-30 11:36 UTC, megicivovic reviewed
This looks really good! lets discuss in daily if there is more to be done 😉

2022-11-30 11:36 UTC, megicivovic commented on travel/src/test/java/com/tx/travel/service/CostCenterServiceImplementationTest.java
> +    assertEquals(expectedMessage, actualMessage);
nice! 💯

2022-11-30 13:57 UTC, petkocfc approved these changes

2022-11-30 13:57 UTC, petkocfc commented on pom.xml
> +                <version>4.5.1</version>
would be nice to see this as property like mockito-core.version or similar but for now it's ok to stay like this

2022-11-30 14:31 UTC, merged